### ISSUE TITLE
Chicago95 Plus! script parsing error when sound themes are included

### ISSUE THREAD

**Issue by EMH-Mark-I** [grassmunk/Chicago95#113]
Output:

```
Microsoft Theme file parser
[Parser] Parsing Theme File: Amiga #1 (16 bit).Theme
[Parser] Parsing Icons
[Parser] Parsing Colors
[Parser] Parsing Cursors
[Parser] Parsing Sounds
[Parser] Parsing Boot (screensaver)
[Parser] Parsing Wallpaper
[Parser] Parsing NonClientMetrics
[Parser] Parsing IconMetrics
[Parser] Parsing Complete!

 ================================================================================

[Theme Builder]	Making folders for theme: Amiga_#1_(16_bit)
[Icons]		Creating new icons in /home/aidan/Downloads/Program Files/Plus!/Themes/Amiga/Amiga_#1_(16_bit)_Chicago95/Amiga_#1_(16_bit)_Icons/
	inkscape will open 14 times to process amiga net neighborhood.svg. (use option -v for more information)
	inkscape will open 21 times to process amiga recycle bin full.svg. (use option -v for more information)
	inkscape will open 8 times to process amiga recycle bin empty.svg. (use option -v for more information)
[Cursors]	Generating New cursors in /home/aidan/Downloads/Program Files/Plus!/Themes/Amiga/Amiga_#1_(16_bit)_Chicago95/Amiga_#1_(16_bit)_Cursors/
[Colors]	Changing theme colors in /home/aidan/Downloads/Program Files/Plus!/Themes/Amiga/Amiga_#1_(16_bit)_Chicago95/Amiga_#1_(16_bit)_Theme/
[Desktop]	Wallpaper: amiga wallpaper.jpg
[Fonts]		Getting any font files
[Colors]	Copying Sounds to /home/aidan/Downloads/Program Files/Plus!/Themes/Amiga/Amiga_#1_(16_bit)_Chicago95/Amiga_#1_(16_bit)_Sounds/
Traceback (most recent call last):
  File "/home/aidan/Documents/gitdir/Chicago95/Plus/Chicago95_Plus.py", line 1216, in <module>
    main()
  File "/home/aidan/Documents/gitdir/Chicago95/Plus/Chicago95_Plus.py", line 1146, in main
    logging.info("Sound: {} copying {} to {}".format(sound,theme_sound_file_name,folder_names['sounds']+new_sound_file_name))
UnboundLocalError: local variable 'theme_sound_file_name' referenced before assignment
```

Can be reproduced with the amiga theme: https://archive.org/details/amiga_201808

Removing the app event sound theme .wav entries resolves the issue as a work around.

**Comment by EMH-Mark-I** [comment]
After further investigation, I think this might be caused by the .wav files missing from the archive. So there's nothing wrong with the script, just that the archived theme is bad.

However, it might be beneficial to check if the specified .wav files are present or missing.

**Comment by grassmunk** [comment]
I'm in the process of a complete rewrite of Plus! to be released this week for terminal, GUI version being worked on. It fixes this among many other things.

**Comment by grassmunk** [comment]
New Plus library fixes this issue
