### ISSUE TITLE
installer doesnt work in arch linux

### ISSUE THREAD

**Issue by aban930** [grassmunk/Chicago95#200]
hello, i get this error

[userraban@archlinux Chicago95-master]$ python3 installer.py 
Traceback (most recent call last):
  File "/home/userraban/Desktop/Chicago95-master/installer.py", line 600, in <module>
    app = InstallGUI()
  File "/home/userraban/Desktop/Chicago95-master/installer.py", line 26, in __init__
    self.set_style()
  File "/home/userraban/Desktop/Chicago95-master/installer.py", line 45, in set_style
    provider.load_from_path(running_folder + "/Theme/Chicago95/gtk-3.0/gtk.css")
gi.repository.GLib.Error: gtk-css-provider-error-quark: gtk.css:142:29Failed to import: Error opening file /home/userraban/Desktop/Chicago95-master/Theme/Chicago95/gtk-3.0/apps/xfce.css: No such file or directory (2)
[userraban@archlinux Chicago95-master]$

**Comment by phil294** [comment]
I am using Manjaro (Arch Linux based) and am not experiencing any such errors when using the graphical installer.
