### ISSUE TITLE
Are there other ways to modify Chicago95 other than using Chicago95 Plus?

### ISSUE THREAD

**Issue by ny8** [grassmunk/Chicago95#241]
Whenever I try installing a theme using Chicago95 Plus I get this error: 
```Installing theme with the following options:
Theme File: /home/otter/Downloads/Program Files/Plus!/Themes/The Honeymooners.theme
Inkscape Options:
	Colors: 32 Overlap: 1 Squaresize: 20
Install Directory: /home/otter/Chicago95/Plus
Paths:
	Cursor Path: /home/otter/.icons/Chicago95_Cursor_Black
	Theme Path: /home/otter/.themes/Chicago95
	Icons Path: /home/otter/.icons/Chicago95
Install (checkbox) Options:
	Cursors: True
	Icons: True
	Wallpaper: False
	Sounds: False
	Colors: True
	Fonts: True
	Screensaver: True
Traceback (most recent call last):
  File "/home/otter/Chicago95/Plus/./PlusGUI.py", line 1207, in install_accept
    self.install_theme()
  File "/home/otter/Chicago95/Plus/./PlusGUI.py", line 1232, in install_theme
    self.theme.go(cursors=self.install_cursors, icons=self.install_icons, wallpaper=self.install_wallpaper, 
  File "/home/otter/Chicago95/Plus/pluslib.py", line 155, in go
    self.generate_theme(cursors, icons, wallpaper, sounds, colors, fonts, screensaver)
  File "/home/otter/Chicago95/Plus/pluslib.py", line 268, in generate_theme
    self.create_icons()
  File "/home/otter/Chicago95/Plus/pluslib.py", line 972, in create_icons
    svg_icon_file = self.convert_icon(self.folder_names['icons'], self.folder_names['icons']+icon_filename)
  File "/home/otter/Chicago95/Plus/pluslib.py", line 2452, in convert_icon
    self.fix_with_inkscape( rgbs[rgb] , tmp_file )
  File "/home/otter/Chicago95/Plus/pluslib.py", line 2511, in fix_with_inkscape
    subprocess.check_call(args, stderr=subprocess.DEVNULL ,stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[b'/usr/bin/inkscape', '-g', '--select=rect4', '--verb', 'EditSelectSameFillColor;SelectionCombine;SelectionUnion;FileSave;FileQuit', '/home/otter/Chicago95/Plus/chicago95_tmp_file.svg']' returned non-zero exit status 1.

```

So im wondering: are there other ways to modify chicago95 other than using the Plus! software? Sorry if this is a dumb question.

**Comment by grassmunk** [comment]
There's not really. This uses a bunch of tools to modify all the colors in the various places. 

Please provide me with the versions below and I'll try and replicate it:

1) Xubuntu Version
2) Inkscape Version

**Comment by Fierelier** [comment]
You can also check out Extras/recolor.py, which I made a while ago. -- But it's basic and not very documented.
