### ISSUE TITLE
Why doesn't Windows Plus themes work?

### ISSUE THREAD

**Issue by TerryTRSPanda** [grassmunk/Chicago95#290]
Here's the output of my Terminal, I don't speak Python, but I noticed it it's looking for a SVG that doesn't exist

`[MakePreview] Generating Preview Image
[MakePreview] Metrics... OK
[MakePreview] Fonts... OK
[MakePreview] Icons... OK
[MakePreview] Wallpaper... OK
[MakePreview] Buttons... OK
[MakePreview] Preview... OK
[MakePreview] Preview Generated
Installing theme with the following options:
Theme File: /home/user/Downloads/Themes/Complete Friends Theme Pack v1.0b (High Color).Theme
Inkscape Options:
	Colors: 32 Overlap: 1 Squaresize: 20
Install Directory: /home/user/Downloads
Paths:
	Cursor Path: /usr/share/icons/Chicago95_Cursor_Black
	Theme Path: /usr/share/themes/Chicago95
	Icons Path: /usr/share/icons/Chicago95
Install (checkbox) Options:
	Cursors: True
	Icons: True
	Wallpaper: True
	Sounds: True
	Colors: True
	Fonts: True
	Screensaver: True
    Pango version: 1.46.2
Traceback (most recent call last):
  File "/usr/bin/PlusGUI", line 1208, in install_accept
    self.install_theme()
  File "/usr/bin/PlusGUI", line 1233, in install_theme
    self.theme.go(cursors=self.install_cursors, icons=self.install_icons, wallpaper=self.install_wallpaper, 
  File "/usr/libexec/chicago95-theme-plus/pluslib.py", line 155, in go
    self.generate_theme(cursors, icons, wallpaper, sounds, colors, fonts, screensaver)
  File "/usr/libexec/chicago95-theme-plus/pluslib.py", line 268, in generate_theme
    self.create_icons()
  File "/usr/libexec/chicago95-theme-plus/pluslib.py", line 972, in create_icons
    svg_icon_file = self.convert_icon(self.folder_names['icons'], self.folder_names['icons']+icon_filename)
  File "/usr/libexec/chicago95-theme-plus/pluslib.py", line 2433, in convert_icon
    svg = ET.parse(tmp_file)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/libexec/chicago95-theme-plus/chicago95_tmp_file.svg'

`

**Comment by Mitchykins** [comment]
https://github.com/grassmunk/Chicago95/issues/243#issuecomment-1548724936

This should offer some solutions, unfortunately it's not perfect.

**Comment by XargonWan** [comment]
Can you try to check if the issues is still there with my PR applied (or in my fork)?
https://github.com/grassmunk/Chicago95/pull/355

**Comment by 266-750Balloons** [comment]
> Can you try to check if the issues is still there with my PR applied (or in my fork)? #355

There's also a good chance this is from the Inkscape compatibility problem fixed with #346.
