### ISSUE TITLE
Re-running installer fails on Chicago95_Panel_Preferences.tar.bz2

### ISSUE THREAD

**Issue by kevgrig** [grassmunk/Chicago95#312]
I just upgraded to Fedora 39 and the theme seemed off so I `git pull`ed the latest `master` branch and re-ran `installer.py` but it hung on `Installing component: Panel` and showed an error in the terminal:

```
[...]
Generating XFCE panel
Installing Panel config from: /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
Traceback (most recent call last):
  File "/work/Chicago95/./installer.py", line 397, in install
    subprocess.check_call(["xfce4-panel-profiles", "load", running_folder+"/Extras/Chicago95_Panel_Preferences.tar.bz2"], stdout=subprocess.DEVNULL)
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xfce4-panel-profiles', 'load', '/work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2']' returned non-zero exit status 1.
```

I'm running everything vanilla for Chicago95 and no extras.

**Comment by LuisPeregrina** [comment]
Can you post the output of running the command? 
`xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2`

**Comment by Alexderoode011202** [comment]
I am on linux mint and am having the exact same problem. This is the output I received which is very similar to yours:

`Installing Panel config from: /tmp/ChicagoStuff22090/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
Traceback (most recent call last):
  File "/tmp/ChicagoStuff22090/Chicago95/./installer.py", line 397, in install
    subprocess.check_call(["xfce4-panel-profiles", "load", running_folder+"/Extras/Chicago95_Panel_Preferences.tar.bz2"], stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xfce4-panel-profiles', 'load', '/tmp/ChicagoStuff22090/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2']' returned non-zero exit status 1.`

**Comment by Alexderoode011202** [comment]
> Can you post the output of running the command? `xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2`

I also try running this command in the folder containing chicago95.
I get told the file does not exist:
`xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2`

**Comment by kevgrig** [comment]
> Can you post the output of running the command? `xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2`

@LuisPeregrina  My apologies. I somehow missed the notification for your question and just saw it because of the other commenter.

I ran that command and there was no output. My panel shifted to my other monitor and so I had to edit its settings and switch the output to my primary monitor again. Otherwise, there were no other changes. Should I re-run the installer?

```sh
$ ls -l /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
-rw-rw-r--. 1 kevin kevin 2382 Apr  8  2022 /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
$ xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
$ 
```

**Comment by kevgrig** [comment]
@LuisPeregrina Realizing now why you had me run that command, I ran it again and printed the return code and it's fine. Let me try the installer again...

```
$ xfce4-panel-profiles load /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
$ echo $?
0
```

**Comment by kevgrig** [comment]
@LuisPeregrina I did a `git pull`, re-ran `installer.py` and this time it worked!

```
Installing Panel config from: /work/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
Install Completed! Enjoy Chicago95!
```

No clue what's different.

**Comment by kevgrig** [comment]
@Alexderoode011202 In your case, you should run:

```
xfce4-panel-profiles load /tmp/ChicagoStuff22090/Chicago95/Extras/Chicago95_Panel_Preferences.tar.bz2
```

In addition to the output of that command, also run:

```
echo $?
```

**Comment by citizenkepler** [comment]
I have found on the Debian 12 XFCE installed os, that the xfce4-panel-profiles tool is not installed by default and causes the panels not to be loaded.

The fix is to apt-get install xfce4-panel-profiles

Then re-run the installer or this command from the git repo directory

xfce4-panel-profiles load Extras/Chicago95_Panel_Preferences.tar.bz2
