### ISSUE TITLE
automatic installer stuck on install_theme (deb12/xfce4.18)

### ISSUE THREAD

**Issue by piqle** [grassmunk/Chicago95#339]
i'm trying to run the installer on a fresh version of debian 12 and having issues with the automated installer.

the process gets stuck on "install_theme"

> Debian 12 (bookworm)
> kernel: 6.1.0-20-amd64
> DE: Xfce 4.18
> WM: Xfwm4

![image](https://github.com/grassmunk/Chicago95/assets/21250149/87df06b6-8bb2-44f9-bb7b-8b5574e47436)

```
> root@arasaka:/home/yami/Downloads/chicago95/Chicago95# ./installer.py 
> Installer running from: /home/yami/Downloads/chicago95/Chicago95
> [PANEL] Warning: xfce4-panel-profiles not installed, manual panel installation required. See INSTALL.md
> Installing Chicago 95 with the following options:
>  Components:
>  	Theme:		True
> 	Icons:		True
> 	Cursors:	True
> 	Background:	True
> 	Sounds:		True
> 	Fonts:		True
>  Customizations:
>  	Thunar Graphics:	True
> 	Change Terminal Colors:	True
> 	Set Bash Prompt:	True
> 	Set zsh promt/theme:	False
> 	Customize Panel:	False
> Installing Chicago 95
> Enabling Theme in XFCE4
> Changing xfconf setting xsettings//Net/ThemeName to Chicago95
> Failed to init libxfconf: The connection is closed.
> Changing xfconf setting xsettings//Net/ThemeName to Chicago95
> Failed to init libxfconf: The connection is closed.
> Traceback (most recent call last):
>   File "/home/yami/Downloads/chicago95/Chicago95/./installer.py", line 440, in xfconf_query
>     subprocess.check_call(args, stdout=subprocess.DEVNULL)
>   File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '[b'/usr/bin/xfconf-query', '--channel', 'xsettings', '--property', '/Net/ThemeName', '--set', 'Chicago95']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/yami/Downloads/chicago95/Chicago95/./installer.py", line 259, in install
>     self.xfconf_query('xsettings', '/Net/ThemeName', "Chicago95")
>   File "/home/yami/Downloads/chicago95/Chicago95/./installer.py", line 452, in xfconf_query
>     subprocess.check_call(args, stdout=subprocess.DEVNULL)	
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '[b'/usr/bin/xfconf-query', '--channel', 'xsettings', '--property', '/Net/ThemeName', '--create', '--type', 'string', '--set', 'Chicago95']' returned non-zero exit status 1.
> 
```

**Comment by piqle** [comment]
**closing:** this seems to be isolated to VMware Workstation.

/facepalm
