### ISSUE TITLE
Mogrify doesn't work

### ISSUE THREAD

**Issue by CPPGhettoIrony** [grassmunk/Chicago95#348]
while applying the theme, mogrify doesn't do what its supposed to

`mogrify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
Traceback (most recent call last):
  File "/home/blenk/git/chicago95/Plus/PlusGUI.py", line 1223, in install_accept
    self.install_theme()
  File "/home/blenk/git/chicago95/Plus/PlusGUI.py", line 1248, in install_theme
    self.theme.go(cursors=self.install_cursors, icons=self.install_icons, wallpaper=self.install_wallpaper, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blenk/git/chicago95/Plus/pluslib.py", line 158, in go
    self.generate_theme(cursors, icons, wallpaper, sounds, colors, fonts, screensaver)
  File "/home/blenk/git/chicago95/Plus/pluslib.py", line 279, in generate_theme
    self.convert_colors()
  File "/home/blenk/git/chicago95/Plus/pluslib.py", line 1273, in convert_colors
    self.change_asset_colors(self.folder_names['theme'], 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blenk/git/chicago95/Plus/pluslib.py", line 1820, in change_asset_colors
    subprocess.check_call(args)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[b'/sbin/mogrify', '-fill', '#000000', '-opaque', '#000000', '-fill', '#a09cb8', '-opaque', '#dfdfdf', '-fill', '#384080', '-opaque', '#808080', '-fill', '#5864b8', '-opaque', '#ffffff', '-fill', '#84a3d2', '-opaque', '#c0c0c0', '-fill', '#ffffff', '-opaque', '#FFFF00', '-quiet', '/home/blenk/git/chicago95/Plus/Vaio1_Chicago95/Vaio1_Theme/gtk-3.0/assets/throbber']' returned non-zero exit status 1.`

**Comment by XargonWan** [comment]
Greetings, I got the same issue

**Comment by XargonWan** [comment]
I proposed a PR to fix this issue: https://github.com/grassmunk/Chicago95/pull/355
