### ISSUE TITLE
Plus! GUI returns KeyError: 'glyphs' when attempting to load a theme

### ISSUE THREAD

**Issue by BlackberrieCake137** [grassmunk/Chicago95#357]
Hi! Themes aren't working for some reason. 

I get the error 

```WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

[MakePreview] Fonts... [MakePreview] Generating Preview Image
[MakePreview] Metrics... OK
Traceback (most recent call last):
  File "/home/admin/Scrivania/.Chicago95/Plus/./PlusGUI.py", line 872, in open_file
    self.preview_image = MakePreview(self.theme)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Scrivania/.Chicago95/Plus/./PlusGUI.py", line 110, in __init__
    self.set_fonts()
  File "/home/admin/Scrivania/.Chicago95/Plus/./PlusGUI.py", line 171, in set_fonts
    self.lfMessageFont = self.get_font(self.msgfont)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Scrivania/.Chicago95/Plus/./PlusGUI.py", line 384, in get_font
    return self.get_font("Noto-Sans-Regular")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Scrivania/.Chicago95/Plus/./PlusGUI.py", line 365, in get_font
    return installed_fonts[fontname]['glyphs']
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'glyphs'```

**Comment by PacoPacorius** [comment]
I am also having this problem on arch linux.

**Comment by BlackberrieCake137** [comment]
> I am also having this problem on arch linux.
> 
> edit: the cli version of this tool seems to be working much better for some reason.

ill try the CLI version shortly

**Comment by grassmunk** [comment]
Could you send me the specific theme you had an issue with?

**Comment by ezvision** [comment]
> Could you send me the specific theme you had an issue with?

I have the same exact error on fedora. Tried multiple themes and they give the same error, both with the gui and with the cli.

this is the most recent one I tried: https://archive.org/details/enlite_202005/enlite.1.png
